import { PrismaClient, Sport, QuestionType } from "@prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";
import { neonConfig } from "@neondatabase/serverless";
import ws from "ws";
import "dotenv/config";

neonConfig.webSocketConstructor = ws;
const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const db = new PrismaClient({ adapter });

type SeedQuestion = {
  sport: Sport;
  type: QuestionType;
  prompt: string;
  choices: string[];
  answer: string;
  difficulty?: number;
  tags?: string[];
};

const questions: SeedQuestion[] = [
  // ─── MLB ─────────────────────────────────────────────────────────────────
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "How many outs are in a full inning (both halves)?",
    choices: ["3", "6", "9", "4"],
    answer: "6",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team has won the most World Series championships?",
    choices: ["New York Yankees", "Boston Red Sox", "Los Angeles Dodgers", "St. Louis Cardinals"],
    answer: "New York Yankees",
    difficulty: 2,
    tags: ["history"],
  },
  {
    sport: "MLB",
    type: "FILL_BLANK",
    prompt: "Barry Bonds holds the all-time MLB record for career home runs with how many?",
    choices: [],
    answer: "762",
    difficulty: 3,
    tags: ["records"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the distance from the pitcher's mound to home plate in feet?",
    choices: ["60 feet 6 inches", "55 feet", "62 feet", "58 feet 6 inches"],
    answer: "60 feet 6 inches",
    difficulty: 2,
    tags: ["rules"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "Which city's MLB team is called the Cubs?",
    choices: ["Chicago", "Detroit", "Cincinnati", "Pittsburgh"],
    answer: "Chicago",
    difficulty: 1,
    tags: ["teams"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "What does 'ERA' stand for in baseball?",
    choices: ["Earned Run Average", "Extra Run Attempt", "Error Rate Average", "Earned Run Assessment"],
    answer: "Earned Run Average",
    difficulty: 1,
    tags: ["stats"],
  },
  {
    sport: "MLB",
    type: "FILL_BLANK",
    prompt: "What year did Jackie Robinson break MLB's color barrier?",
    choices: [],
    answer: "1947",
    difficulty: 2,
    tags: ["history"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "Which pitcher holds the MLB record for most career strikeouts?",
    choices: ["Nolan Ryan", "Randy Johnson", "Roger Clemens", "Steve Carlton"],
    answer: "Nolan Ryan",
    difficulty: 2,
    tags: ["records", "pitching"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "How many balls result in a walk (base on balls)?",
    choices: ["4", "3", "5", "2"],
    answer: "4",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the maximum number of players allowed on an MLB roster during the regular season?",
    choices: ["26", "25", "28", "30"],
    answer: "26",
    difficulty: 3,
    tags: ["rules"],
  },
  {
    sport: "MLB",
    type: "FILL_BLANK",
    prompt: "Cal Ripken Jr. set the record for consecutive games played with how many games?",
    choices: [],
    answer: "2632",
    difficulty: 3,
    tags: ["records"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team plays its home games at Fenway Park?",
    choices: ["Boston Red Sox", "New York Yankees", "Baltimore Orioles", "Toronto Blue Jays"],
    answer: "Boston Red Sox",
    difficulty: 1,
    tags: ["teams", "stadiums"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the term for hitting a home run with the bases loaded?",
    choices: ["Grand Slam", "Inside-the-Park", "Walk-off", "Cycle"],
    answer: "Grand Slam",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "MLB",
    type: "FILL_BLANK",
    prompt: "A perfect game in baseball requires the pitcher to retire how many batters in a row?",
    choices: [],
    answer: "27",
    difficulty: 2,
    tags: ["rules", "pitching"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "Which MLB team is based in Houston, Texas?",
    choices: ["Houston Astros", "Texas Rangers", "Oakland Athletics", "Seattle Mariners"],
    answer: "Houston Astros",
    difficulty: 1,
    tags: ["teams"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "What does 'OPS' stand for in baseball statistics?",
    choices: ["On-base Plus Slugging", "Overall Player Score", "On-base Percentage + Slugging", "Offensive Production Stat"],
    answer: "On-base Plus Slugging",
    difficulty: 3,
    tags: ["stats"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "Ty Cobb's career batting average of .366 is the highest in MLB history. What position did he primarily play?",
    choices: ["Center Field", "Left Field", "First Base", "Shortstop"],
    answer: "Center Field",
    difficulty: 3,
    tags: ["history"],
  },
  {
    sport: "MLB",
    type: "FILL_BLANK",
    prompt: "How many players are on the field for a defensive team in baseball?",
    choices: [],
    answer: "9",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team won the 2016 World Series, ending a 108-year championship drought?",
    choices: ["Chicago Cubs", "Cleveland Indians", "Boston Red Sox", "San Francisco Giants"],
    answer: "Chicago Cubs",
    difficulty: 2,
    tags: ["history"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the infield fly rule primarily designed to prevent?",
    choices: ["Easy double plays on infield pop-ups", "Catcher interference", "Balk violations", "Hit-by-pitch disputes"],
    answer: "Easy double plays on infield pop-ups",
    difficulty: 4,
    tags: ["rules"],
  },
  {
    sport: "MLB",
    type: "FILL_BLANK",
    prompt: "Hank Aaron held the MLB home run record for 33 years with how many career homers?",
    choices: [],
    answer: "755",
    difficulty: 3,
    tags: ["records"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "Which MLB division do the New York Mets belong to?",
    choices: ["NL East", "AL East", "NL Central", "AL Central"],
    answer: "NL East",
    difficulty: 2,
    tags: ["teams"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the name of the award given to the best pitcher in each league annually?",
    choices: ["Cy Young Award", "MVP Award", "Rolaids Relief Award", "Gold Glove"],
    answer: "Cy Young Award",
    difficulty: 1,
    tags: ["awards"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "Which stadium has a 'Green Monster' in left field?",
    choices: ["Fenway Park", "Wrigley Field", "Yankee Stadium", "Dodger Stadium"],
    answer: "Fenway Park",
    difficulty: 2,
    tags: ["stadiums"],
  },
  {
    sport: "MLB",
    type: "FILL_BLANK",
    prompt: "How many innings are in a standard MLB game?",
    choices: [],
    answer: "9",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "The MLB's 'Triple Crown' refers to a batter leading their league in which three categories?",
    choices: [
      "Batting Average, Home Runs, RBI",
      "Home Runs, Stolen Bases, RBI",
      "Batting Average, On-base %, Slugging",
      "Home Runs, Strikeouts, Walks",
    ],
    answer: "Batting Average, Home Runs, RBI",
    difficulty: 3,
    tags: ["stats"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team plays in the American League West division?",
    choices: ["Los Angeles Angels", "Seattle Mariners", "Houston Astros", "All of the above"],
    answer: "All of the above",
    difficulty: 3,
    tags: ["teams"],
  },
  {
    sport: "MLB",
    type: "FILL_BLANK",
    prompt: "Pete Rose holds the MLB record for career hits with how many?",
    choices: [],
    answer: "4256",
    difficulty: 3,
    tags: ["records"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "What is a 'no-hitter' in baseball?",
    choices: [
      "A game where the pitcher allows no hits",
      "A shutout victory",
      "A game with no errors",
      "A win with zero strikeouts",
    ],
    answer: "A game where the pitcher allows no hits",
    difficulty: 2,
    tags: ["rules", "pitching"],
  },
  {
    sport: "MLB",
    type: "MULTIPLE_CHOICE",
    prompt: "The designated hitter (DH) rule was originally adopted by which league in 1973?",
    choices: ["American League", "National League", "Both leagues simultaneously", "Pacific Coast League"],
    answer: "American League",
    difficulty: 3,
    tags: ["history", "rules"],
  },

  // ─── NFL ─────────────────────────────────────────────────────────────────
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "How many points is a touchdown worth in the NFL?",
    choices: ["6", "7", "3", "8"],
    answer: "6",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "FILL_BLANK",
    prompt: "How many yards does a team need to advance the ball to earn a new set of downs?",
    choices: [],
    answer: "10",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which quarterback has won the most Super Bowl rings?",
    choices: ["Tom Brady", "Joe Montana", "Terry Bradshaw", "Peyton Manning"],
    answer: "Tom Brady",
    difficulty: 2,
    tags: ["records"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "How many players does each NFL team have on the field during a play?",
    choices: ["11", "10", "12", "9"],
    answer: "11",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "The Super Bowl trophy is officially named after which legendary coach?",
    choices: ["Vince Lombardi", "Chuck Noll", "Bill Walsh", "Tom Landry"],
    answer: "Vince Lombardi",
    difficulty: 2,
    tags: ["history"],
  },
  {
    sport: "NFL",
    type: "FILL_BLANK",
    prompt: "An NFL football field is how many yards long from end zone to end zone?",
    choices: [],
    answer: "100",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team plays their home games at Lambeau Field?",
    choices: ["Green Bay Packers", "Minnesota Vikings", "Chicago Bears", "Detroit Lions"],
    answer: "Green Bay Packers",
    difficulty: 1,
    tags: ["teams", "stadiums"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the maximum number of players allowed on an NFL active roster?",
    choices: ["53", "52", "55", "50"],
    answer: "53",
    difficulty: 3,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "How long is each quarter in an NFL game?",
    choices: ["15 minutes", "12 minutes", "20 minutes", "10 minutes"],
    answer: "15 minutes",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "FILL_BLANK",
    prompt: "The Pittsburgh Steelers have won how many Super Bowls (the most by any franchise)?",
    choices: [],
    answer: "6",
    difficulty: 3,
    tags: ["records"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "What is a 'safety' worth in the NFL?",
    choices: ["2 points", "1 point", "3 points", "6 points"],
    answer: "2 points",
    difficulty: 2,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which running back holds the NFL record for career rushing yards?",
    choices: ["Emmitt Smith", "Barry Sanders", "Walter Payton", "Adrian Peterson"],
    answer: "Emmitt Smith",
    difficulty: 2,
    tags: ["records"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team is known as 'America's Team'?",
    choices: ["Dallas Cowboys", "New York Giants", "San Francisco 49ers", "Chicago Bears"],
    answer: "Dallas Cowboys",
    difficulty: 1,
    tags: ["teams"],
  },
  {
    sport: "NFL",
    type: "FILL_BLANK",
    prompt: "How many seconds does the offense have to snap the ball before a delay-of-game penalty?",
    choices: [],
    answer: "40",
    difficulty: 3,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "What does 'PAT' stand for after a touchdown?",
    choices: ["Point After Touchdown", "Post-score Action Time", "Play After Touchdown", "Penalty After TD"],
    answer: "Point After Touchdown",
    difficulty: 2,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which city has an NFL team called the Chiefs?",
    choices: ["Kansas City", "Indianapolis", "Denver", "Houston"],
    answer: "Kansas City",
    difficulty: 1,
    tags: ["teams"],
  },
  {
    sport: "NFL",
    type: "FILL_BLANK",
    prompt: "Jerry Rice holds the NFL record for career receiving touchdowns with how many?",
    choices: [],
    answer: "197",
    difficulty: 4,
    tags: ["records"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "How many points is a field goal worth?",
    choices: ["3", "2", "6", "1"],
    answer: "3",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the name of the annual NFL draft where teams select college players?",
    choices: ["NFL Draft", "Player Selection Meeting", "College Combine", "Rookie Showcase"],
    answer: "NFL Draft",
    difficulty: 1,
    tags: ["general"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which conference plays the AFC Championship game?",
    choices: ["American Football Conference", "Atlantic Football Conference", "American Field Conference", "Advanced Football Conference"],
    answer: "American Football Conference",
    difficulty: 2,
    tags: ["general"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "The New England Patriots play their home games in which state?",
    choices: ["Massachusetts", "Connecticut", "New Hampshire", "Rhode Island"],
    answer: "Massachusetts",
    difficulty: 2,
    tags: ["teams"],
  },
  {
    sport: "NFL",
    type: "FILL_BLANK",
    prompt: "A regulation NFL football must be between how many inches in long circumference? (Enter the minimum value)",
    choices: [],
    answer: "28",
    difficulty: 5,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team won the first-ever Super Bowl in 1967?",
    choices: ["Green Bay Packers", "Kansas City Chiefs", "Dallas Cowboys", "Oakland Raiders"],
    answer: "Green Bay Packers",
    difficulty: 3,
    tags: ["history"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "How many downs does a team have to advance 10 yards before punting or turning over the ball?",
    choices: ["4", "3", "5", "6"],
    answer: "4",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which position is responsible for snapping the ball to the quarterback?",
    choices: ["Center", "Guard", "Tight End", "Fullback"],
    answer: "Center",
    difficulty: 2,
    tags: ["positions"],
  },
  {
    sport: "NFL",
    type: "FILL_BLANK",
    prompt: "The NFL was founded in what year?",
    choices: [],
    answer: "1920",
    difficulty: 3,
    tags: ["history"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the penalty for intentional grounding in the NFL?",
    choices: [
      "Loss of down and 10 yards",
      "Automatic safety",
      "Loss of down only",
      "Ejection of QB",
    ],
    answer: "Loss of down and 10 yards",
    difficulty: 4,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team is nicknamed the 'Steel Curtain' based on their legendary 1970s defense?",
    choices: ["Pittsburgh Steelers", "Chicago Bears", "Minnesota Vikings", "Dallas Cowboys"],
    answer: "Pittsburgh Steelers",
    difficulty: 2,
    tags: ["history"],
  },
  {
    sport: "NFL",
    type: "FILL_BLANK",
    prompt: "Peyton Manning threw how many touchdown passes in his record-setting 2013 season?",
    choices: [],
    answer: "55",
    difficulty: 4,
    tags: ["records"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the width of the NFL goal post in feet?",
    choices: ["18.5 feet", "20 feet", "15 feet", "16 feet"],
    answer: "18.5 feet",
    difficulty: 4,
    tags: ["rules"],
  },
  {
    sport: "NFL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which NFL team has won the most consecutive division titles?",
    choices: [
      "New England Patriots",
      "Green Bay Packers",
      "Kansas City Chiefs",
      "Pittsburgh Steelers",
    ],
    answer: "New England Patriots",
    difficulty: 4,
    tags: ["records"],
  },

  // ─── NBA ─────────────────────────────────────────────────────────────────
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "How many points does a three-pointer count for in the NBA?",
    choices: ["3", "2", "4", "1"],
    answer: "3",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NBA",
    type: "FILL_BLANK",
    prompt: "How many players are on the court per team during an NBA game?",
    choices: [],
    answer: "5",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "Which player is known as 'The King' and has won four NBA championships?",
    choices: ["LeBron James", "Kobe Bryant", "Kevin Durant", "Shaquille O'Neal"],
    answer: "LeBron James",
    difficulty: 1,
    tags: ["players"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team has the most NBA championships?",
    choices: ["Boston Celtics", "Los Angeles Lakers", "Chicago Bulls", "Golden State Warriors"],
    answer: "Boston Celtics",
    difficulty: 3,
    tags: ["history"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "How long is each quarter in an NBA game?",
    choices: ["12 minutes", "10 minutes", "15 minutes", "8 minutes"],
    answer: "12 minutes",
    difficulty: 2,
    tags: ["rules"],
  },
  {
    sport: "NBA",
    type: "FILL_BLANK",
    prompt: "How many personal fouls does it take to foul out in the NBA?",
    choices: [],
    answer: "6",
    difficulty: 2,
    tags: ["rules"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "Who holds the NBA record for most career points?",
    choices: ["LeBron James", "Kareem Abdul-Jabbar", "Karl Malone", "Kobe Bryant"],
    answer: "LeBron James",
    difficulty: 3,
    tags: ["records"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "The NBA's three-point line was introduced in the 1979–80 season. What team won the title that year?",
    choices: ["Los Angeles Lakers", "Boston Celtics", "Philadelphia 76ers", "Seattle SuperSonics"],
    answer: "Los Angeles Lakers",
    difficulty: 4,
    tags: ["history"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team plays its home games at Madison Square Garden?",
    choices: ["New York Knicks", "Brooklyn Nets", "Boston Celtics", "Philadelphia 76ers"],
    answer: "New York Knicks",
    difficulty: 1,
    tags: ["teams", "stadiums"],
  },
  {
    sport: "NBA",
    type: "FILL_BLANK",
    prompt: "Wilt Chamberlain famously scored how many points in a single NBA game in 1962?",
    choices: [],
    answer: "100",
    difficulty: 3,
    tags: ["records"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "How many seconds does an NBA team have to advance the ball past half-court?",
    choices: ["8 seconds", "10 seconds", "5 seconds", "15 seconds"],
    answer: "8 seconds",
    difficulty: 3,
    tags: ["rules"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "Michael Jordan won how many NBA championships with the Chicago Bulls?",
    choices: ["6", "5", "4", "7"],
    answer: "6",
    difficulty: 2,
    tags: ["history"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "Which player is nicknamed 'The Splash Brothers' along with Klay Thompson?",
    choices: ["Stephen Curry", "Draymond Green", "Kevin Durant", "Andrew Wiggins"],
    answer: "Stephen Curry",
    difficulty: 2,
    tags: ["players"],
  },
  {
    sport: "NBA",
    type: "FILL_BLANK",
    prompt: "An NBA basketball court is how many feet long?",
    choices: [],
    answer: "94",
    difficulty: 3,
    tags: ["rules"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the shot clock duration in the NBA?",
    choices: ["24 seconds", "30 seconds", "20 seconds", "35 seconds"],
    answer: "24 seconds",
    difficulty: 2,
    tags: ["rules"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team did Magic Johnson and Kareem Abdul-Jabbar lead to five championships in the 1980s?",
    choices: ["Los Angeles Lakers", "Boston Celtics", "Detroit Pistons", "Philadelphia 76ers"],
    answer: "Los Angeles Lakers",
    difficulty: 2,
    tags: ["history"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "What term describes a shot made at the buzzer at the end of a period?",
    choices: ["Buzzer-beater", "Last-second shot", "Game-winner", "Overtime trigger"],
    answer: "Buzzer-beater",
    difficulty: 1,
    tags: ["terms"],
  },
  {
    sport: "NBA",
    type: "FILL_BLANK",
    prompt: "The NBA was founded in what year?",
    choices: [],
    answer: "1946",
    difficulty: 3,
    tags: ["history"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "Which NBA team is located in Miami, Florida?",
    choices: ["Miami Heat", "Orlando Magic", "Charlotte Hornets", "Atlanta Hawks"],
    answer: "Miami Heat",
    difficulty: 1,
    tags: ["teams"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the maximum number of players on an NBA roster?",
    choices: ["15", "12", "13", "17"],
    answer: "15",
    difficulty: 3,
    tags: ["rules"],
  },
  {
    sport: "NBA",
    type: "FILL_BLANK",
    prompt: "How high is a regulation NBA basketball hoop from the floor in feet?",
    choices: [],
    answer: "10",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "Which player won the NBA MVP award five times, more than anyone else?",
    choices: ["Kareem Abdul-Jabbar", "Michael Jordan", "Bill Russell", "LeBron James"],
    answer: "Kareem Abdul-Jabbar",
    difficulty: 3,
    tags: ["awards"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "What does 'PER' stand for in basketball statistics?",
    choices: ["Player Efficiency Rating", "Points and Efficiency Ratio", "Personal Efficiency Record", "Performance Evaluation Rating"],
    answer: "Player Efficiency Rating",
    difficulty: 3,
    tags: ["stats"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "The NBA All-Star Game is traditionally held during which month?",
    choices: ["February", "January", "March", "December"],
    answer: "February",
    difficulty: 2,
    tags: ["general"],
  },
  {
    sport: "NBA",
    type: "FILL_BLANK",
    prompt: "The Golden State Warriors won how many championships between 2015 and 2022?",
    choices: [],
    answer: "4",
    difficulty: 3,
    tags: ["history"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team did Shaquille O'Neal and Kobe Bryant win three consecutive championships with?",
    choices: ["Los Angeles Lakers", "Miami Heat", "Orlando Magic", "Phoenix Suns"],
    answer: "Los Angeles Lakers",
    difficulty: 2,
    tags: ["history"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "A 'triple-double' in basketball means a player achieved double figures in which three categories?",
    choices: ["Points, Rebounds, Assists", "Points, Steals, Blocks", "Assists, Rebounds, Steals", "Points, Assists, Steals"],
    answer: "Points, Rebounds, Assists",
    difficulty: 2,
    tags: ["stats", "terms"],
  },
  {
    sport: "NBA",
    type: "FILL_BLANK",
    prompt: "How many teams are in the NBA?",
    choices: [],
    answer: "30",
    difficulty: 2,
    tags: ["general"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "Stephen Curry broke the single-season three-pointer record in 2015–16 with how many threes?",
    choices: ["402", "286", "330", "350"],
    answer: "402",
    difficulty: 4,
    tags: ["records"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "What rule requires a player to keep one foot in bounds when catching a pass near the sideline?",
    choices: [
      "NBA requires two feet in bounds",
      "One foot is sufficient in college",
      "In bounds rule",
      "Only the ball must be in bounds",
    ],
    answer: "NBA requires two feet in bounds",
    difficulty: 4,
    tags: ["rules"],
  },
  {
    sport: "NBA",
    type: "MULTIPLE_CHOICE",
    prompt: "Which franchise retired the number 23 in honor of Michael Jordan?",
    choices: ["Chicago Bulls", "Washington Wizards", "Both A and B", "Miami Heat"],
    answer: "Both A and B",
    difficulty: 4,
    tags: ["players"],
  },

  // ─── NHL ─────────────────────────────────────────────────────────────────
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "How many players from each team are on the ice during normal play (excluding goalies)?",
    choices: ["5", "6", "4", "3"],
    answer: "5",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NHL",
    type: "FILL_BLANK",
    prompt: "How many minutes is each period in an NHL game?",
    choices: [],
    answer: "20",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "The Stanley Cup is awarded to the champion of which league?",
    choices: ["NHL", "AHL", "ECHL", "KHL"],
    answer: "NHL",
    difficulty: 1,
    tags: ["general"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which player is known as 'The Great One' and holds virtually every NHL scoring record?",
    choices: ["Wayne Gretzky", "Mario Lemieux", "Gordie Howe", "Bobby Orr"],
    answer: "Wayne Gretzky",
    difficulty: 1,
    tags: ["players"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "How long is a minor penalty in hockey?",
    choices: ["2 minutes", "5 minutes", "4 minutes", "3 minutes"],
    answer: "2 minutes",
    difficulty: 2,
    tags: ["rules"],
  },
  {
    sport: "NHL",
    type: "FILL_BLANK",
    prompt: "Wayne Gretzky's career goal total in the NHL is how many? (Regular season only)",
    choices: [],
    answer: "894",
    difficulty: 4,
    tags: ["records"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which city's NHL team is called the Maple Leafs?",
    choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
    answer: "Toronto",
    difficulty: 1,
    tags: ["teams"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "What is an 'icing' call in hockey?",
    choices: [
      "Shooting the puck from behind the center line past the opponent's goal line without a touch",
      "A player intentionally icing their hand",
      "A goalie freezing the puck",
      "A line change during active play",
    ],
    answer: "Shooting the puck from behind the center line past the opponent's goal line without a touch",
    difficulty: 3,
    tags: ["rules"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "The Montreal Canadiens have won the most Stanley Cup championships. How many?",
    choices: ["24", "13", "17", "21"],
    answer: "24",
    difficulty: 4,
    tags: ["records"],
  },
  {
    sport: "NHL",
    type: "FILL_BLANK",
    prompt: "A standard NHL puck weighs how many ounces?",
    choices: [],
    answer: "6",
    difficulty: 3,
    tags: ["rules"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the Vezina Trophy awarded for in the NHL?",
    choices: ["Best Goaltender", "Most Points Scored", "Best Defenseman", "Top Rookie"],
    answer: "Best Goaltender",
    difficulty: 2,
    tags: ["awards"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team plays its home games at the Bell Centre?",
    choices: ["Montreal Canadiens", "Ottawa Senators", "Toronto Maple Leafs", "Quebec Nordiques"],
    answer: "Montreal Canadiens",
    difficulty: 2,
    tags: ["teams", "stadiums"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "What is an 'offsides' call in hockey?",
    choices: [
      "A player enters the attacking zone before the puck",
      "Too many players on the ice",
      "A delayed penalty situation",
      "A goalie leaving the crease",
    ],
    answer: "A player enters the attacking zone before the puck",
    difficulty: 2,
    tags: ["rules"],
  },
  {
    sport: "NHL",
    type: "FILL_BLANK",
    prompt: "How many periods are there in a regulation NHL game?",
    choices: [],
    answer: "3",
    difficulty: 1,
    tags: ["rules"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "What is the Calder Trophy awarded for?",
    choices: ["Best Rookie", "Best Coach", "Most Goals", "Most Assists"],
    answer: "Best Rookie",
    difficulty: 2,
    tags: ["awards"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which position in hockey has the primary job of preventing goals?",
    choices: ["Goaltender", "Defenseman", "Center", "Right Wing"],
    answer: "Goaltender",
    difficulty: 1,
    tags: ["positions"],
  },
  {
    sport: "NHL",
    type: "FILL_BLANK",
    prompt: "A hockey net is how many feet wide?",
    choices: [],
    answer: "6",
    difficulty: 2,
    tags: ["rules"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "What does 'hat trick' mean in hockey?",
    choices: ["3 goals by one player in one game", "3 assists in one game", "Scoring in 3 straight games", "A defensive shutout"],
    answer: "3 goals by one player in one game",
    difficulty: 2,
    tags: ["terms"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team won the first modern-era Stanley Cup in 1927?",
    choices: ["Ottawa Senators", "Toronto Arenas", "Montreal Canadiens", "Detroit Red Wings"],
    answer: "Ottawa Senators",
    difficulty: 5,
    tags: ["history"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which number did Wayne Gretzky wear throughout most of his NHL career?",
    choices: ["99", "9", "66", "88"],
    answer: "99",
    difficulty: 1,
    tags: ["players"],
  },
  {
    sport: "NHL",
    type: "FILL_BLANK",
    prompt: "The NHL season typically begins in what month?",
    choices: [],
    answer: "October",
    difficulty: 2,
    tags: ["general"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "The Hart Trophy is given to the NHL player judged most valuable to his team. Who has won it most?",
    choices: ["Wayne Gretzky", "Gordie Howe", "Mario Lemieux", "Bobby Orr"],
    answer: "Wayne Gretzky",
    difficulty: 3,
    tags: ["awards"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "What is a 'power play' in hockey?",
    choices: [
      "When one team has more players on ice due to a penalty",
      "A high-speed breakaway",
      "A delayed penalty shot",
      "A goalie pulled for an extra skater",
    ],
    answer: "When one team has more players on ice due to a penalty",
    difficulty: 2,
    tags: ["rules", "terms"],
  },
  {
    sport: "NHL",
    type: "FILL_BLANK",
    prompt: "How many teams are in the NHL?",
    choices: [],
    answer: "32",
    difficulty: 2,
    tags: ["general"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "The NHL was founded in what year?",
    choices: ["1917", "1926", "1910", "1920"],
    answer: "1917",
    difficulty: 3,
    tags: ["history"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which defenseman is considered the greatest of all time and revolutionized the position by rushing the puck?",
    choices: ["Bobby Orr", "Nicklas Lidstrom", "Doug Harvey", "Ray Bourque"],
    answer: "Bobby Orr",
    difficulty: 2,
    tags: ["players"],
  },
  {
    sport: "NHL",
    type: "FILL_BLANK",
    prompt: "A major penalty in hockey lasts how many minutes?",
    choices: [],
    answer: "5",
    difficulty: 2,
    tags: ["rules"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "Which team plays in the Metropolitan Division of the NHL?",
    choices: ["New York Rangers", "Boston Bruins", "Toronto Maple Leafs", "Winnipeg Jets"],
    answer: "New York Rangers",
    difficulty: 3,
    tags: ["teams"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "What happens during a 'penalty shot' in hockey?",
    choices: [
      "A player skates alone against the goalie from center ice",
      "A free kick from the blue line",
      "A 2-on-0 breakaway",
      "A delayed penalty call",
    ],
    answer: "A player skates alone against the goalie from center ice",
    difficulty: 2,
    tags: ["rules"],
  },
  {
    sport: "NHL",
    type: "MULTIPLE_CHOICE",
    prompt: "Mario Lemieux won the Stanley Cup twice with which team?",
    choices: ["Pittsburgh Penguins", "Montreal Canadiens", "Detroit Red Wings", "Edmonton Oilers"],
    answer: "Pittsburgh Penguins",
    difficulty: 2,
    tags: ["history"],
  },
  {
    sport: "NHL",
    type: "FILL_BLANK",
    prompt: "The Stanley Cup was donated by which Governor General of Canada?",
    choices: [],
    answer: "Lord Stanley",
    difficulty: 4,
    tags: ["history"],
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  // Clear existing data
  await db.dailySetQuestion.deleteMany();
  await db.dailySet.deleteMany();
  await db.attemptAnswer.deleteMany();
  await db.attempt.deleteMany();
  await db.question.deleteMany();

  const created = await db.question.createMany({ data: questions });
  console.log(`✅ Created ${created.count} questions`);

  const counts = await db.question.groupBy({ by: ["sport"], _count: true });
  for (const c of counts) {
    console.log(`   ${c.sport}: ${c._count} questions`);
  }

  console.log("✅ Seed complete!");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
